name: oskarschmidt
favicon: null
layout_spectrum: 0.6655768880154938
typography_spectrum: 0.13142224587500095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.41660936549305916
  lightness: 0.4854613596107811
  saturation: 0.897033634595573
  rhythmicContrast: 0.3531718358863145
purpose: []
